/*const searchResults = [
    {
      id_biens: 1,
      description: "Description 1",
      type_bien: "Type 1",
      adresse: "Address 1",
      ville: "City 1",
      code_postal: ["Code 1"],
      prix_estime: 100.0,
      etat: "State 1",
      id_proprietaire: 1,
      Proprietaire: "Proprietaire 1",
      biens_loue: [],
      biens_vip: null,
    },
    {
      id_biens: 2,
      description: "Description 2",
      type_bien: "Type 2",
      adresse: "Address 2",
      ville: "City 2",
      code_postal: ["Code 2"],
      prix_estime: 200.0,
      etat: "State 2",
      id_proprietaire: 2,
      Proprietaire: "Proprietaire 2",
      biens_loue: [],
      biens_vip: null,
    },
    {
        id_biens: 3,
        description: "Description 3",
        type_bien: "Type 3",
        adresse: "Address 3",
        ville: "City 3",
        code_postal: ["Code 3"],
        prix_estime: 200.0,
        etat: "State 3",
        id_proprietaire: 3,
        Proprietaire: "Proprietaire 3",
        biens_loue: [],
        biens_vip: null,
      },
      {
        id_biens: 5,
        description: "Description 5",
        type_bien: "Type 5",
        adresse: "Address 5",
        ville: "City 5",
        code_postal: ["Code 5"],
        prix_estime: 100.0,
        etat: "State 5",
        id_proprietaire: 5,
        Proprietaire: "Proprietaire 5",
        biens_loue: [],
        biens_vip: null,
      },
    // Add more items as needed
  ];
  
  export default searchResults;
  */