import Head from "next/head";
import React, { Fragment, useState } from "react";
import FooterAdmin from "./Footer_admin";
import HeaderAdmin from "./Header_admin";
import SidebarAdmin from "./Sidebar_admin";

const LayoutAdmin = ({children, title="Sample Title"}) => {
     //console.log("layout", title)
     const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
     


  return (
    <Fragment>
      
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <div className="flex bg-gray-100 min-h-screen relative">
        
          <SidebarAdmin mobileNavsidebar={mobileNavsidebar} />
          
          <div className="flex-grow text-gray-800">
          <HeaderAdmin mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar} />
              {children}
          </div>

        <FooterAdmin />
      </div> 
        

    </Fragment>
  );
};

export default LayoutAdmin;